from scrapy import cmdline

# cmdline.execute("scrapy crawl pornhub_spider".split())
# cmdline.execute("scrapy crawl zzcartoon_spider".split())
# cmdline.execute("scrapy crawl nhentai_spider".split())
# cmdline.execute("scrapy crawl 69_story_spider".split())
# cmdline.execute("scrapy crawl book3k_spider".split())
# cmdline.execute("scrapy crawl abc111_spider".split())
# cmdline.execute("scrapy crawl hentaifox_spider -s JOBDIR=crawls/hentaifox".split())
# cmdline.execute("scrapy crawl luscious_spider -s JOBDIR=crawls/luscious".split())
# cmdline.execute("scrapy crawl sis_spider -s JOBDIR=crawls/sis".split())
# cmdline.execute("scrapy crawl beautylegmm_spider -s JOBDIR=crawls/beautylegmm".split())
# cmdline.execute("scrapy crawl tu11_spider -s JOBDIR=crawls/tu11".split())
# cmdline.execute("scrapy crawl tgirl_spider -s JOBDIR=crawls/tgirl".split())
cmdline.execute("scrapy crawl meitulu_spider -s JOBDIR=crawls/meitulu".split())
